"""updated tables

Revision ID: 0a05fdb9a57d
Revises: 793349de1930
Create Date: 2026-06-17 09:27:43.154673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a05fdb9a57d'
down_revision: Union[str, Sequence[str], None] = '793349de1930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('extraction_field_confidence_reviewed_by_fkey'), 'extraction_field_confidence', type_='foreignkey')
    op.drop_column('extraction_field_confidence', 'corrected_value')
    op.drop_column('extraction_field_confidence', 'reviewed_by')
    op.drop_column('extraction_field_confidence', 'reviewed_at')
    op.drop_constraint(op.f('invoices_assigned_to_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'assigned_to')
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchase_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchase_orders', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchase_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('invoices', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invoices_assigned_to_fkey'), 'invoices', 'users', ['assigned_to'], ['id'])
    op.add_column('extraction_field_confidence', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('extraction_field_confidence', sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('extraction_field_confidence', sa.Column('corrected_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('extraction_field_confidence_reviewed_by_fkey'), 'extraction_field_confidence', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###
