"""updated tables

Revision ID: 793349de1930
Revises: a0af5abf4327
Create Date: 2026-06-17 05:04:13.970598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793349de1930'
down_revision: Union[str, Sequence[str], None] = 'a0af5abf4327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_line_po_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_line_item_id', sa.Uuid(), nullable=False),
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('po_line_item_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT_CODE', 'LLM_FUZZY', 'SPLIT', 'MANUAL', name='allocationmatchtype'), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_item_id'], ['invoice_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('audit_log_invoice_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_log', 'updated_at')
    op.drop_constraint(op.f('dispute_communications_dispute_id_fkey'), 'dispute_communications', type_='foreignkey')
    op.create_foreign_key(None, 'dispute_communications', 'disputes', ['dispute_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dispute_communications', 'updated_at')
    op.alter_column('disputes', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('disputes_invoice_id_fkey'), 'disputes', type_='foreignkey')
    op.create_foreign_key(None, 'disputes', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('extraction_field_confidence_invoice_id_fkey'), 'extraction_field_confidence', type_='foreignkey')
    op.create_foreign_key(None, 'extraction_field_confidence', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('extraction_field_confidence', 'updated_at')
    op.add_column('invoice_extracted_vendor', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('invoice_extracted_vendor', 'is_vendor_name_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_extracted_vendor', 'is_gstin_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_extracted_vendor', 'is_bank_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_extracted_vendor', 'is_ifsc_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_extracted_vendor', 'is_vendor_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('invoice_extracted_vendor_invoice_id_fkey'), 'invoice_extracted_vendor', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_extracted_vendor', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.add_column('invoice_line_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('invoice_line_items', 'item_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_item_code_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_unauthorized_extra_item',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_hsn_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_line_total_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_unit_price_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_quantity_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_uom_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoice_line_items', 'is_tax_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('invoice_line_items_invoice_id_fkey'), 'invoice_line_items', type_='foreignkey')
    op.drop_constraint(op.f('invoice_line_items_po_line_item_id_fkey'), 'invoice_line_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_line_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_line_items', 'po_line_item_id')
    op.drop_constraint(op.f('invoice_po_mapping_invoice_id_fkey'), 'invoice_po_mapping', type_='foreignkey')
    op.drop_constraint(op.f('invoice_po_mapping_po_id_fkey'), 'invoice_po_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_po_mapping', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoice_po_mapping', 'purchase_orders', ['po_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_po_mapping', 'updated_at')
    op.drop_constraint(op.f('invoice_self_checks_invoice_id_fkey'), 'invoice_self_checks', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_self_checks', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_self_checks', 'updated_at')
    op.drop_constraint(op.f('invoice_validation_issues_invoice_id_fkey'), 'invoice_validation_issues', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_validation_issues', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_validation_issues', 'updated_at')
    op.add_column('invoices', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('invoices', 'is_high_value',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invoices', 'is_partial_invoice',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('po_line_items', 'item_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('po_line_items', 'pending_billed_quantity')
    op.add_column('purchase_orders', sa.Column('company_id', sa.Uuid(), nullable=False))
    op.alter_column('purchase_orders', 'delivery_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'purchase_orders', 'company_master', ['company_id'], ['id'])
    op.drop_column('purchase_orders', 'client_name')
    op.drop_column('purchase_orders', 'pending_billed_amount')
    op.drop_column('purchase_orders', 'client_gstin')
    op.drop_column('purchase_orders', 'client_address')
    op.add_column('vendor_master', sa.Column('company_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'vendor_master', 'company_master', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vendor_master_company_id_fkey'), 'vendor_master', type_='foreignkey')
    op.drop_column('vendor_master', 'company_id')
    op.add_column('purchase_orders', sa.Column('client_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('client_gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('pending_billed_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('purchase_orders_company_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.alter_column('purchase_orders', 'delivery_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('purchase_orders', 'company_id')
    op.add_column('po_line_items', sa.Column('pending_billed_quantity', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False))
    op.alter_column('po_line_items', 'item_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('invoices', 'is_partial_invoice',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoices', 'is_high_value',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('invoices', 'assigned_at')
    op.add_column('invoice_validation_issues', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('invoice_validation_issues_invoice_id_fkey'), 'invoice_validation_issues', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_validation_issues_invoice_id_fkey'), 'invoice_validation_issues', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoice_self_checks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('invoice_self_checks_invoice_id_fkey'), 'invoice_self_checks', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_self_checks_invoice_id_fkey'), 'invoice_self_checks', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoice_po_mapping', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('invoice_po_mapping_invoice_id_fkey'), 'invoice_po_mapping', type_='foreignkey')
    op.drop_constraint(op.f('invoice_po_mapping_po_id_fkey'), 'invoice_po_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_po_mapping_po_id_fkey'), 'invoice_po_mapping', 'purchase_orders', ['po_id'], ['id'])
    op.create_foreign_key(op.f('invoice_po_mapping_invoice_id_fkey'), 'invoice_po_mapping', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoice_line_items', sa.Column('po_line_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('invoice_line_items_invoice_id_fkey'), 'invoice_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_line_items_po_line_item_id_fkey'), 'invoice_line_items', 'po_line_items', ['po_line_item_id'], ['id'])
    op.create_foreign_key(op.f('invoice_line_items_invoice_id_fkey'), 'invoice_line_items', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoice_line_items', 'is_tax_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_uom_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_quantity_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_unit_price_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_line_total_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_hsn_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_unauthorized_extra_item',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'is_item_code_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('invoice_line_items', 'item_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('invoice_line_items', 'created_at')
    op.drop_constraint(op.f('invoice_extracted_vendor_invoice_id_fkey'), 'invoice_extracted_vendor', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_extracted_vendor_invoice_id_fkey'), 'invoice_extracted_vendor', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoice_extracted_vendor', 'is_vendor_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_extracted_vendor', 'is_ifsc_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_extracted_vendor', 'is_bank_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_extracted_vendor', 'is_gstin_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invoice_extracted_vendor', 'is_vendor_name_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('invoice_extracted_vendor', 'created_at')
    op.add_column('extraction_field_confidence', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('extraction_field_confidence_invoice_id_fkey'), 'extraction_field_confidence', type_='foreignkey')
    op.create_foreign_key(op.f('extraction_field_confidence_invoice_id_fkey'), 'extraction_field_confidence', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(op.f('disputes_invoice_id_fkey'), 'disputes', type_='foreignkey')
    op.create_foreign_key(op.f('disputes_invoice_id_fkey'), 'disputes', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('disputes', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('dispute_communications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('dispute_communications_dispute_id_fkey'), 'dispute_communications', type_='foreignkey')
    op.create_foreign_key(op.f('dispute_communications_dispute_id_fkey'), 'dispute_communications', 'disputes', ['dispute_id'], ['id'])
    op.add_column('audit_log', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('audit_log_invoice_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_invoice_id_fkey'), 'audit_log', 'invoices', ['invoice_id'], ['id'])
    op.drop_table('invoice_line_po_allocations')
    # ### end Alembic commands ###
