"""remove_company_id_from_vendor_master

Revision ID: 9778b1d16f77
Revises: e8f1c2a4b5d6
Create Date: 2026-06-18 09:14:14.451035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9778b1d16f77'
down_revision: Union[str, Sequence[str], None] = 'e8f1c2a4b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
