"""create gmail monitoring state table

Revision ID: a0af5abf4327
Revises: b7d23095578e
Create Date: 2026-06-13 07:14:03.165939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0af5abf4327'
down_revision: Union[str, Sequence[str], None] = 'b7d23095578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_monitoring_state',
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('last_processed_history_id', sa.BigInteger(), nullable=False),
    sa.Column('is_monitoring', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('email_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_monitoring_state')
    # ### end Alembic commands ###
