"""remove_company_id_from_vendor_master

Revision ID: fe34f2763bf8
Revises: 9778b1d16f77
Create Date: 2026-06-18 09:19:40.198611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe34f2763bf8'
down_revision: Union[str, Sequence[str], None] = '9778b1d16f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vendor_master_company_id_fkey'), 'vendor_master', type_='foreignkey')
    op.drop_column('vendor_master', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_master', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('vendor_master_company_id_fkey'), 'vendor_master', 'company_master', ['company_id'], ['id'])
    # ### end Alembic commands ###
